name: Checks

on:
  push:
    branches:
      - '*'

jobs:
  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask pylint black

      - name: Code Lint and Style Check
        run: |
          pylint app/app.py
          black --check app/app.py

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install cli-markdown
        run: npm i -g cli-markdown

      - name: Check Markdown
        run: md README.md

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install Flask  # Add other dependencies if needed for your tests

      - name: Run Unit Tests
        run: python -m unittest discover -s app -p '*_test.py'

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Check for hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: "mariawasilewa"
          token: ${{ secrets.SONARCLOUD_TOKEN }}
          projectKey: "mariawasilewa_devops"

      - name: Build and Analyze
        run: |
          # Your build commands here (e.g., compile, build, etc.)
          # Example for a Python project:
          python -m pip install -r requirements.txt
          sonar-scanner

